### ISSUE TITLE
chrome 配置mr，点击提交没有任何反应

### ISSUE THREAD

**Issue by termzh** [zkl2333/MR-Extension#10]
点击提及没有反馈，不知道是不是使用方法的问题

**Comment by xzwangjian** [comment]
我这边情况也一样。mr版本1.9.37。

**Comment by foxcatweb** [comment]
同版本1.9.37 应该是你使用方法问题 地址我填写的内网MR的地址 密钥需要先去MR应用设置里API密钥管理里添加一个 然后插件里填你添加这个密钥 就提交成功 正常使用了

**Comment by termzh** [comment]
> 1.9.37应该是你使用方法问题问题的的的的的的的的的密钥密钥需要需要需要先先去去去去去去去里里里里里了
非常感谢，确实是我自己的使用的问题！
