### ISSUE TITLE
憨憨站点设置失败：登录失败，但实际浏览器是正常访问的

### ISSUE THREAD

**Issue by termzh** [zkl2333/MR-Extension#11]
憨憨在浏览器是已登录并且正常访问的，但是提交失败

**Comment by ruicky** [comment]
有没有可能 是憨憨的站点配置文件有更新。不是插件的锅？

> 憨憨在浏览器是已登录并且正常访问的，但是提交失败

**Comment by termzh** [comment]
好的，谢谢！但插件应该是集成了配置文件吧，最后还是得需要插件作者进行更新吧，毕竟我们自己没办法在插件里自行更新配置文件

**Comment by termzh** [comment]
> 有没有可能 是憨憨的站点配置文件有更新。不是插件的锅？
> 
> > 憨憨在浏览器是已登录并且正常访问的，但是提交失败
好的，谢谢！但插件应该是集成了配置文件吧，最后还是得需要插件作者进行更新吧，毕竟我们自己没办法在插件里自行更新配置文件

**Comment by zkl2333** [comment]
> > 有没有可能 是憨憨的站点配置文件有更新。不是插件的锅？
> > > 憨憨在浏览器是已登录并且正常访问的，但是提交失败
> > > 好的，谢谢！但插件应该是集成了配置文件吧，最后还是得需要插件作者进行更新吧，毕竟我们自己没办法在插件里自行更新配置文件

读取的是mr的信息 登录失败是mr报告的错误 你在mr点保存也是这个错 插件没有内置配置文件

**Comment by zkl2333** [comment]
请到mr更新配置文件 https://github.com/htnanako/movie-robot-public/blob/main/app/sites/hhan.yml

**Comment by termzh** [comment]
> 请到mr更新配置文件 https://github.com/htnanako/movie-robot-public/blob/main/app/sites/hhan.yml

解决了，谢谢解答！是我对这个插件的理解有问题。
我更换了最新的配置文件，我一直用的就是这个项目的配置文件，我看憨憨的配置文件昨天是有更新的，不知道为啥我的本地没有自动更新
